// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sgl
SEXP sgl(SEXP R_C, SEXP R_D, SEXP R_B, const int& maxIter, SEXP R_lambda1, SEXP R_lambda2, const int& nl, const double& eps, const int& singled, const int& pos, const int& dslices);
RcppExport SEXP sgen_sgl(SEXP R_CSEXP, SEXP R_DSEXP, SEXP R_BSEXP, SEXP maxIterSEXP, SEXP R_lambda1SEXP, SEXP R_lambda2SEXP, SEXP nlSEXP, SEXP epsSEXP, SEXP singledSEXP, SEXP posSEXP, SEXP dslicesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type R_C(R_CSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_D(R_DSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_B(R_BSEXP );
        Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_lambda1(R_lambda1SEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_lambda2(R_lambda2SEXP );
        Rcpp::traits::input_parameter< const int& >::type nl(nlSEXP );
        Rcpp::traits::input_parameter< const double& >::type eps(epsSEXP );
        Rcpp::traits::input_parameter< const int& >::type singled(singledSEXP );
        Rcpp::traits::input_parameter< const int& >::type pos(posSEXP );
        Rcpp::traits::input_parameter< const int& >::type dslices(dslicesSEXP );
        SEXP __result = sgl(R_C, R_D, R_B, maxIter, R_lambda1, R_lambda2, nl, eps, singled, pos, dslices);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// smtl
SEXP smtl(SEXP R_C, SEXP R_D, SEXP R_B, const int& maxIter, SEXP R_lambda, SEXP R_lambda1, SEXP R_lambda2, const int& nl, const double& eps, const int& singled, const int& pos, const int& dslices);
RcppExport SEXP sgen_smtl(SEXP R_CSEXP, SEXP R_DSEXP, SEXP R_BSEXP, SEXP maxIterSEXP, SEXP R_lambdaSEXP, SEXP R_lambda1SEXP, SEXP R_lambda2SEXP, SEXP nlSEXP, SEXP epsSEXP, SEXP singledSEXP, SEXP posSEXP, SEXP dslicesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type R_C(R_CSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_D(R_DSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_B(R_BSEXP );
        Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_lambda(R_lambdaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_lambda1(R_lambda1SEXP );
        Rcpp::traits::input_parameter< SEXP >::type R_lambda2(R_lambda2SEXP );
        Rcpp::traits::input_parameter< const int& >::type nl(nlSEXP );
        Rcpp::traits::input_parameter< const double& >::type eps(epsSEXP );
        Rcpp::traits::input_parameter< const int& >::type singled(singledSEXP );
        Rcpp::traits::input_parameter< const int& >::type pos(posSEXP );
        Rcpp::traits::input_parameter< const int& >::type dslices(dslicesSEXP );
        SEXP __result = smtl(R_C, R_D, R_B, maxIter, R_lambda, R_lambda1, R_lambda2, nl, eps, singled, pos, dslices);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
