# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgl <- function(R_C, R_D, R_B, maxIter, R_lambda1, R_lambda2, nl, eps, singled, pos, dslices) {
    .Call('sgen_sgl', PACKAGE = 'sgen', R_C, R_D, R_B, maxIter, R_lambda1, R_lambda2, nl, eps, singled, pos, dslices)
}

smtl <- function(R_C, R_D, R_B, maxIter, R_lambda, R_lambda1, R_lambda2, nl, eps, singled, pos, dslices) {
    .Call('sgen_smtl', PACKAGE = 'sgen', R_C, R_D, R_B, maxIter, R_lambda, R_lambda1, R_lambda2, nl, eps, singled, pos, dslices)
}

